### ISSUE TITLE
エラー

### ISSUE THREAD

**Issue by kuroneko6423** [kuroneko6423/Minecraft-server-info-bot#4]
/home/ubuntu/node_modules/discord.js/src/client/Client.js:548
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (/home/ubuntu/node_modules/discord.js/src/client/Client.js:548:13)
    at new Client (/home/ubuntu/node_modules/discord.js/src/client/Client.js:76:10)
    at Object.<anonymous> (/home/ubuntu/BOT/Minecraft-info-bot/bot.js:46:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
}

**Comment by ap12-code** [comment]
Bot側のインテントはあってますか?

**Comment by kuroneko6423** [comment]
すべて有効ですね
